In [1]:
import pandas as pd 
from pathlib import Path

In [2]:
df = pd.read_parquet(r"D:\ProyectoAnalisisElectrico\BarrasEstaciones\infraestructura_consolidada.parquet")
cl_path = Path(r"D:\ProyectoAnalisisElectrico\ClientesLibres")
cl = pd.read_csv(cl_path/"Base_Final_CupraTherm_ACTECOS_SII_Clientes_Libres_CEN_RUT_REGION_2025.csv",sep=",")
cli = pd.read_excel(cl_path/"2025-12-CLIENTES-Libres-Inf-33-TDLC.xlsx",sheet_name="Clientes Libres",skiprows=3)

In [ ]:
cli.head()

In [ ]:
barras_cli = cli["BARRA"].drop_duplicates()

In [ ]:
df.head()

In [ ]:
cl.columns

In [ ]:
barras_regiones = cl[["BARRAS_CEN_RUT_REGION","REGION_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA","BARRA_CANDIDATA_METODO"]]
barras_regiones.head()

In [24]:
cli_located = pd.merge(left=barras_cli, right=df, left_on="BARRA", right_on="nombre_barra_cmg", how="left")

In [27]:
cli_located[cli_located["macrozona"].isna()]

,BARRA,nombre_barra,nombre_barra_cmg,tension,region,provincia,macrozona,confianza,IA
408,RECINTO_______013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
cli_located.head()

,BARRA,nombre_barra,nombre_barra_cmg,tension,region,provincia,macrozona,confianza,IA
0,A.BLANCAS_____013,A.BLANCAS,A.BLANCAS_____013,13.0,Biobío,Concepción,Centro Sur,100.0,False
1,A.HOSPICIO____013,A.HOSPICIO,A.HOSPICIO____013,13.0,Tarapacá,Iquique,Norte Grande,100.0,False
2,A.HOSPICIO____110,A.HOSPICIO,A.HOSPICIO____110,110.0,Tarapacá,Iquique,Norte Grande,100.0,False
3,A.JAHUEL______066,A.JAHUEL,A.JAHUEL______066,66.0,Metropolitana de Santiago,Maipo,Centro,100.0,False
4,A_DE_CORDOVA__013,A_DE_CORDOVA,A_DE_CORDOVA__013,13.0,Metropolitana de Santiago,Santiago,Centro,100.0,False

In [29]:
cl.columns

Index(['CODIGO_VU', 'RAZON_SOCIAL', 'RUT_RAZON_SOCIAL',
       'NOMBRE_ESTABLECIMIENTO', 'COMBUSTIBLE_PRIMARIO', 'LATITUD', 'LONGITUD',
       'REGION', 'RUBRO', 'CIIU6', 'DEMANDA_CALOR_MWH', 'CALNUM', 'Acrolein',
       'Arsenic', 'Benzene', 'Cadmium', 'Carbon dioxide', 'Carbon monoxide',
       'Formaldehyde', 'Lead', 'Mercury', 'Methane', 'Nitrogen oxides (NOx)',
       'Nitrous oxide', 'Pentachlorophenol (PCP)', 'Sulfur dioxide', 'Toluene',
       'Volatile organic compounds (VOC)', 'Black Carbon', 'PCDD-F',
       'Sulfur oxides (SOx)', 'Ammonia', 'PM, primary', 'PM10, primary',
       'PM2.5, primary', 'MATCH_ACTECOS_SII', 'N_ACTIVIDADES_SII',
       'CODIGOS_ACTIVIDAD_SII', 'DESC_ACTIVIDAD_ECONOMICA_SII',
       'FECHAS_ACTIVIDAD_SII', 'AFECTA_IVA_SII', 'CATEGORIA_TRIBUTARIA_SII',
       'RUT_CLEAN', 'REGION_KEY', 'MATCH_ACTECOS_SII_BOOL',
       'N_ESTABLECIMIENTOS_RUT_REGION', 'CODIGOS_VU_RUT_REGION',
       'ESTABLECIMIENTOS_RUT_REGION', 'RUT_CLIENTE_CEN',
       'RAZON_SOCIAL_CLIENTE_CEN', 'SUBESTACION_REGION_CEN',
       'SUMINISTRADOR_CEN_RUT_REGION', 'CONECTADO_A_LA_RED_DE_CEN_RUT_REGION',
       'BARRAS_CEN_RUT_REGION', 'SUBESTACIONES_CEN_RUT_REGION',
       'NEMOTECNICOS_SUBESTACIONES_CEN_RUT_REGION',
       'COMUNAS_SUBESTACIONES_CEN_RUT_REGION',
       'PROVINCIAS_SUBESTACIONES_CEN_RUT_REGION',
       'SUBESTACION_MATCH_STATUS_CEN_RUT_REGION',
       'CONSUMO_TOTAL_MWH_2025_CEN_RUT_REGION', 'ene-25_MWH_CEN_RUT_REGION',
       'feb-25_MWH_CEN_RUT_REGION', 'mar-25_MWH_CEN_RUT_REGION',
       'abr-25_MWH_CEN_RUT_REGION', 'may-25_MWH_CEN_RUT_REGION',
       'jun-25_MWH_CEN_RUT_REGION', 'jul-25_MWH_CEN_RUT_REGION',
       'ago-25_MWH_CEN_RUT_REGION', 'sept-25_MWH_CEN_RUT_REGION',
       'oct-25_MWH_CEN_RUT_REGION', 'nov-25_MWH_CEN_RUT_REGION',
       'dic-25_MWH_CEN_RUT_REGION', 'N_BARRAS_CEN_RUT_REGION',
       'N_SUBESTACIONES_CEN_RUT_REGION', 'N_FILAS_CEN_CONSOLIDADAS_RUT_REGION',
       'N_FILAS_CEN_ORIGINALES_RUT_REGION', 'CLIENTE_LIBRE_CEN_REGION',
       'CLIENTE_LIBRE_CEN', 'CASO_GRANULARIDAD_CEN_REGION',
       'REQUIERE_REVISION_GEO', 'BARRA_CEN_CANDIDATA_MAS_CERCANA',
       'SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'NEMOTECNICO_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'REGION_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'COMUNA_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'PROVINCIA_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'LATITUD_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'LONGITUD_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'DISTANCIA_KM_EST_SUBESTACION_CEN_CANDIDATA_MAS_CERCANA',
       'CONSUMO_TOTAL_MWH_2025_CEN_BARRA_CANDIDATA', 'BARRA_CANDIDATA_METODO'],
      dtype='object')

In [5]:
cl["BARRAS_CEN_RUT_REGION"]

0      LO_VALLEDOR___013 | PAJARITOS_____013
1      ALTO_BONITO___023 | DALCAHUE______023
2                          N.VICTORIA____220
3                          ALTO_BONITO___023
4      BUIN__________013 | SAN_BERNARDO__013
                       ...
410    B.BLANCO______023 | OSORNO________013
411                        LIN.NORTE_____013
412    LAS_ACACIAS___013 | SAN_BERNARDO__013
413    LAS_ACACIAS___013 | SAN_BERNARDO__013
414                        BUIN__________013
Name: BARRAS_CEN_RUT_REGION, Length: 415, dtype: object