In [1]:
import pandas as pd
from pathlib import Path

In [21]:
retiros = pd.read_parquet(Path(r"D:\ProyectoAnalisisElectrico\DiaPromedio\Mensuales\2604\2604_mean_month.parquet"))
ventas = pd.read_excel(Path(r"D:\ProyectoAnalisisElectrico\TransferenciasEconomicas\Ventas_SEN_2026_v2.xlsx"), sheet_name = "DATA")
calor = pd.read_csv(Path(r"D:\ProyectoAnalisisElectrico\CupraThermV2\Resumen_Establecimientos.csv"), sep=",")

In [22]:
ventas = ventas[(ventas["MES"] == 4) & ((ventas["TIPO"] == "L") | (ventas["TIPO"] == "L_D"))]

In [23]:
ventas.head()

,AÑO,MES,RECONOCE EL RETIRO EN BALANCES DE TRANSFERENCIAS_O,CLIENTE SUMINISTRADO POR_O,CLIENTE2,RUTCLIENTE,TIPO,REGION,SECTOR,SUBSECTOR,PUNTO DE CONEXIÓN,ENERGIA2,RECONOCE EL RETIRO EN BALANCES DE TRANSFERENCIAS,CLIENTE SUMINISTRADO POR,RUTCLIENTEPUNTO DE CONEXIÓN,CLIENTE,RETIRO,clave,ID_PC
26786,2026,4,ACCIONA ENERGIA CHILE HOLDINGS S.A.,ACCIONA ENERGIA CHILE HOLDINGS S.A.,Compañía Exploradora y Explotadora Minera Chil...,82789400-1,L,Atacama,Minero,Minas Varias,Cerrillos 023,6220.655212,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,82789400-1Cerrillos 023,Compañía Exploradora y Explotadora Minera Chil...,6220.655212,COEMIN,9615.0
26787,2026,4,ACCIONA ENERGIA CHILE HOLDINGS S.A.,ACCIONA ENERGIA CHILE HOLDINGS S.A.,EMPRESA NACIONAL DE MINERIA,61703000-4,L,Atacama,Minero,Minas Varias,Cardones 110,3780.501498,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,61703000-4Cardones 110,EMPRESA NACIONAL DE MINERIA,3780.501498,L_EN005,3626.0
26788,2026,4,ACCIONA ENERGIA CHILE HOLDINGS S.A.,ACCIONA ENERGIA CHILE HOLDINGS S.A.,NUEVA ATACAMA S.A.,76850128-9,L,Atacama,Industrial,Industrias Varias,Caldera 110,1588.785145,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,ACCIONA ENERGÍA CHILE HOLDINGS S.A.,76850128-9Caldera 110,NUEVA ATACAMA S.A.,1588.785145,L_ECONSSA_COPIAPO,13251.0
26789,2026,4,ACIERTA ENERGIA SPA,ACIERTA ENERGIA SPA,COMPAÑÍA MINERA MARICUNGA,78095890-1,L,Atacama,Minero,Cobre,Cardones 110,230.732133,ACIERTA ENERGIA SPA,ACIERTA ENERGIA SPA,78095890-1Cardones 110,COMPAÑÍA MINERA MARICUNGA,230.732133,REFU,14694.0
26790,2026,4,ACIERTA ENERGIA SPA,ACIERTA ENERGIA SPA,ODATA CHILE SPA,77128355-1,L,Metropolitana De Santiago,"Comercial, Público, Residencial (CPR)",Comercial,Lampa 220,2354.233474,ACIERTA ENERGIA SPA,ACIERTA ENERGIA SPA,77128355-1Lampa 220,ODATA CHILE SPA,2354.233474,ODATA_ACIERTA,14220.0

In [29]:
ventas["REGION"].unique()

array(['Atacama', 'Metropolitana De Santiago', 'Antofagasta', 'Tarapacá',
       'Coquimbo', 'Bío Bío', 'Biobío', 'Maule', 'Ñuble', 'La Araucania',
       'Valparaíso', "Libertador Bernardo O'Higgins", 'Los Ríos',
       'La Araucanía', 'Arica y Parinacota', 'Los Lagos'], dtype=object)

In [30]:
calor["REGION"].unique()

array(['Metropolitana de Santiago', 'Los Lagos', 'Antofagasta',
       'Tarapacá', "Libertador Gral. Bernardo O'Higgins", 'Valparaíso',
       'Maule', 'Ñuble', 'Biobío', 'Araucanía', 'Arica y Parinacota',
       'Magallanes y de la Antártica Chilena', 'Coquimbo', 'Los Ríos',
       'Atacama', 'Aysén del Gral. Carlos Ibañez del Campo'], dtype=object)

In [27]:
ventas_de_calor = ventas[ventas["RUTCLIENTE"].isin(calor["RUT_RAZON_SOCIAL"])]

In [28]:
len(ventas_de_calor)

898

In [24]:
retiros.head()

,clave,nombre_barra,tension,Zona,Razon_Social,RUT,Nombre_Corto,Hora,Año_Mes,tipo,medida_mean,medida_std,medida_count,CMg[CLP/KWh]_mean,CMg[CLP/KWh]_std,CMg[CLP/KWh]_count,valorizado_CLP_mean,valorizado_CLP_std,valorizado_CLP_count
0,36142444,A.HOSPICIO,13,Norte Distribución,AES Andes S.A.,94.272.000-9,AES_GENER,0,2026-04-01,L_D,-34.687333,5.328211,30,59.916328,23.144517,30,-2054.780674,716.766954,30
1,36142444,A.HOSPICIO,13,Norte Distribución,AES Andes S.A.,94.272.000-9,AES_GENER,1,2026-04-01,L_D,-34.981333,5.568136,30,57.561499,17.147293,30,-1996.613521,564.665144,30
2,36142444,A.HOSPICIO,13,Norte Distribución,AES Andes S.A.,94.272.000-9,AES_GENER,2,2026-04-01,L_D,-34.916000,5.281187,30,55.868689,10.379477,30,-1939.438042,420.299120,30
3,36142444,A.HOSPICIO,13,Norte Distribución,AES Andes S.A.,94.272.000-9,AES_GENER,3,2026-04-01,L_D,-35.532000,5.433184,30,56.733861,7.576556,30,-2015.793714,409.786530,30
4,36142444,A.HOSPICIO,13,Norte Distribución,AES Andes S.A.,94.272.000-9,AES_GENER,4,2026-04-01,L_D,-34.244000,5.416390,30,57.101189,5.612341,30,-1943.196694,259.967700,30

In [25]:
retiros_con_ventas = retiros[retiros["clave"].isin(ventas["clave"])]

In [26]:
print(len(retiros_con_ventas))
print(len(retiros))

133800
151584