In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

sii_path = Path(r"D:\ProyectoAnalisisElectrico\SII\ActividadesEconomicasMayo2026\PUB_NOM_ACTECOS.txt")
sii = pd.read_csv(sii_path,sep="\t")

carpeta_datos = Path(r"D:\ProyectoAnalisisElectrico\DiaPromedio\Periodos\2505_2604")
print("Cargando versión Porcentual...")
df = pd.read_parquet(carpeta_datos / "2505_2604_clustered_porcentual.parquet")

Cargando versión Porcentual...

In [2]:
df[["NDV", "DV"]] = df["RUT"].str.replace(".", "", regex=False).str.split("-", expand=True)
df["NDV"] = df["NDV"].astype(int)

In [3]:
df["RUT"].head()

0    96.505.760-9
1    96.505.760-9
2    96.505.760-9
3    96.505.760-9
4    96.505.760-9
Name: RUT, dtype: object

In [4]:
df[["NDV", "DV"]].head()

        NDV DV
0  96505760  9
1  96505760  9
2  96505760  9
3  96505760  9
4  96505760  9

In [5]:
df1 = pd.merge(left=df, right=sii, how="left", left_on=["NDV","DV"], right_on=["RUT","DV"])

In [6]:
df1.head()

,clave,Zona,Hora,active_calendar,RUT_x,rut_log,n_ruts,Razon_Social,razon_social_log,n_razones_sociales,...,dtw_window,dtw_normalize,NDV,DV,RUT_y,CODIGO ACTIVIDAD,DESC. ACTIVIDAD ECONOMICA,FECHA,AFECTA A IVA,CATEGORIA TRIBUTARIA
0,$C$439,Norte,0,111111111111,96.505.760-9,96.505.760-9,1,Colbún S.A.,Colbún S.A.,1,...,3,False,96505760,9,96505760,351011,GENERACION DE ENERGIA ELECTRICA EN CENTRALES H...,01-01-1993,S,1
1,$C$439,Norte,0,111111111111,96.505.760-9,96.505.760-9,1,Colbún S.A.,Colbún S.A.,1,...,3,False,96505760,9,96505760,351012,GENERACION DE ENERGIA ELECTRICA EN CENTRALES T...,20-03-2008,S,1
2,$C$439,Norte,0,111111111111,96.505.760-9,96.505.760-9,1,Colbún S.A.,Colbún S.A.,1,...,3,False,96505760,9,96505760,351019,GENERACION DE ENERGIA ELECTRICA EN OTRAS CENTR...,08-09-2021,S,1
3,$C$439,Norte,0,111111111111,96.505.760-9,96.505.760-9,1,Colbún S.A.,Colbún S.A.,1,...,3,False,96505760,9,96505760,351020,TRANSMISION DE ENERGIA ELECTRICA,01-01-1993,S,1
4,$C$439,Norte,0,111111111111,96.505.760-9,96.505.760-9,1,Colbún S.A.,Colbún S.A.,1,...,3,False,96505760,9,96505760,351030,DISTRIBUCION DE ENERGIA ELECTRICA,01-01-1993,S,1

In [7]:
df1 = df1.drop(columns="RUT_y")

In [8]:
df1[df1["CODIGO ACTIVIDAD"].isna()]

Empty DataFrame
Columns: [clave, Zona, Hora, active_calendar, RUT_x, rut_log, n_ruts, Razon_Social, razon_social_log, n_razones_sociales, Nombre_Corto, nombre_corto_log, n_nombres_cortos, nombre_barra, nombre_barra_log, n_nombres_barra, tension, tension_log, n_tensiones, tipo, period, medida_mean, medida_std, CMg[CLP/KWh]_mean, CMg[CLP/KWh]_std, CMg[CLP/KWh]_count, valorizado_CLP_mean, valorizado_CLP_std, valorizado_CLP_count, medida_total, region, macrozona, confianza, IA, medida_porcentual, clave_unica, id_cluster, metodo_cluster, dtw_window, dtw_normalize, NDV, DV, CODIGO ACTIVIDAD, DESC. ACTIVIDAD ECONOMICA, FECHA, AFECTA A IVA, CATEGORIA TRIBUTARIA]
Index: []

[0 rows x 47 columns]

In [ ]:
df1.to_parquet(carpeta_datos / "2505_2604_clustered_porcentual_sii.parquet", engine='pyarrow')

In [10]:
df1.to_csv(carpeta_datos / "2505_2604_clustered_porcentual_sii.csv", sep=";")